//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================


// USER INCLUDES
#include <SI_EFM8UB2_Register_Enums.h>

//-----------------------------------------------------------------------------
// Global Constants
//-----------------------------------------------------------------------------

#define SYSCLK       24000000          // Internal oscillator frequency in Hz

#define CEX0_FREQUENCY 10000           // Frequency to output in Hz
#define DIVIDE_RATIO (SYSCLK/CEX0_FREQUENCY/2) // SYSCLK cycles per interrupt

//-----------------------------------------------------------------------------
// Global Variables
//-----------------------------------------------------------------------------

extern uint16_t NEXT_COMPARE_VALUE;       // Next edge to be sent out in HSO mode

//-----------------------------------------------------------------------------
// PCA0_ISR
//-----------------------------------------------------------------------------
// This is the ISR for the PCA.  It handles the case when a match occurs on
// channel 0, and updates the PCA0CPn compare register with the value held in
// the global variable "NEXT_COMPARE_VALUE".
//-----------------------------------------------------------------------------
SI_INTERRUPT(PCA0_ISR, PCA0_IRQn)
{
  if (PCA0CN0_CCF0)                           // If Module 0 caused the interrupt
  {
     PCA0CN0_CCF0 = 0;                        // Clear module 0 interrupt flag.

     PCA0CPL0 = (NEXT_COMPARE_VALUE & 0x00FF);
     PCA0CPH0 = (NEXT_COMPARE_VALUE & 0xFF00)>>8;

     // Set up the variable for the following edge
     NEXT_COMPARE_VALUE = PCA0CP0 + DIVIDE_RATIO;
  }
  else                                // Interrupt was caused by other bits.
  {
     PCA0CN0 &= ~0x86;                 // Clear other interrupt flags for PCA
  }
}



