// This file is generated by Xpress Configurator, and will be overwritten when
// saving your Xpress Configurator project!

#ifndef __CPT213B_A01_GM_INIT_H__
#define __CPT213B_A01_GM_INIT_H__

typedef struct
{                                       //  Min-Max |  Default
  uint8_t reserved_0[3];                //      0-0 |       0
  uint8_t active_threshold[13];         //    1-100 |      70
  uint8_t inactive_threshold[13];       //    1-100 |      50
  uint8_t average_touch_delta[13];      //    1-255 |      44
  uint8_t accumulation[13];             //      0-5 |       2
  uint8_t gain[13];                     //      0-7 |       7
  uint8_t reserved_1[4];                //      0-0 |       0
  uint8_t button_debounce;              //     1-15 |       3
  uint8_t active_mode_mask[2];          //      0-1 |       0
  uint8_t reserved_2[14];               //      0-0 |       0
  uint8_t i2c_slave_address;            //    0-255 |     224
  uint8_t reserved_3;                   //      0-0 |       0
  uint8_t i2c_timeout_duration;         //     0-15 |       1
  uint8_t cs00_sensor_string[10];       //          |  "CS00"
  uint8_t cs01_sensor_string[10];       //          |  "CS01"
  uint8_t cs02_sensor_string[10];       //          |  "CS02"
  uint8_t cs03_sensor_string[10];       //          |  "CS03"
  uint8_t cs04_sensor_string[10];       //          |  "CS04"
  uint8_t cs05_sensor_string[10];       //          |  "CS05"
  uint8_t cs06_sensor_string[10];       //          |  "CS06"
  uint8_t cs07_sensor_string[10];       //          |  "CS07"
  uint8_t cs08_sensor_string[10];       //          |  "CS08"
  uint8_t cs09_sensor_string[10];       //          |  "CS09"
  uint8_t cs10_sensor_string[10];       //          |  "CS10"
  uint8_t cs11_sensor_string[10];       //          |  "CS11"
  uint8_t cs12_sensor_string[10];       //          |  "CS12"
} config_profile_t;


// This structure must be transmitted to the CPT device in Big-endian format!
#define CPT213B_A01_GM_DEFAULT_CONFIG \
{ \
  {0x00, 0x00, 0x00},                                                              /* reserved_0 */ \
  {0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46, 0x46},  /* Active Threshold */ \
  {0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E, 0x1E},  /* Inactive Threshold */ \
  {0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C},  /* Average Touch Delta */ \
  {0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03},  /* Accumulation */ \
  {0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06},  /* Gain */ \
  {0x00, 0x00, 0x00, 0x00},                                                        /* reserved_1 */ \
  0x02,                                                                            /* Button Debounce */ \
  {0xFF, 0x1F},                                                                    /* Active Mode Mask */ \
  {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},  /* reserved_2 */ \
  0xF0,                                                                            /* I2C slave address */ \
  0x00,                                                                            /* reserved_3 */ \
  0x01,                                                                            /* I2C timeout duration */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS00 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS01 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS02 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS03 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS04 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS05 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS06 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS07 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS08 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS09 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS10 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS11 sensor string */ \
  {'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'},  /* CS12 sensor string */ \
}

#define CPT213B_A01_GM_DEFAULT_CONFIG_CHECKSUM (0xB570)

#endif // CPT213B_A01_GM_INIT_H__
