//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>
#include "adc_0.h"

//-----------------------------------------------------------------------------
// RTC0ALARM_ISR
//-----------------------------------------------------------------------------
//
// This ISR serves merely to break the device out of Idle mode.
//
// RTC0ALARM ISR Content goes here. Remember to clear flag bits:
// RTC0CN0::ALRM (RTC Alarm Event Flag and Auto Reset Enable)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(RTC0ALARM_ISR, RTC0ALARM_IRQn)
{
}

