/*
 * Silicon Laboratories Confidential
 * Copyright 2011 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#include "..\..\..\master_bsp.h"
SI_SEGMENT_VARIABLE( Si4455ChipPend, uint8_t, SI_SEG_BDATA );
SI_SEGMENT_VARIABLE( Si4455PhPend, uint8_t, SI_SEG_BDATA );
SI_SEGMENT_VARIABLE( Si4455ModemPend, uint8_t, SI_SEG_BDATA );
#define BITS(bitArray, bitPos)  BIT bitArray ## bitPos
#define WRITE_TO_BIT_ARRAY(bitArray, byte)  bitArray ## 0 = byte & 0x01; \
                                            bitArray ## 1 = byte & 0x02; \
                                            bitArray ## 2 = byte & 0x04; \
                                            bitArray ## 3 = byte & 0x08; \
                                            bitArray ## 4 = byte & 0x10; \
                                            bitArray ## 5 = byte & 0x20; \
                                            bitArray ## 6 = byte & 0x40;
                                           // bitArray ## 7 = byte & 0x80;

#define Si4455DummyChipPend0 					Si4455ChipPend0
#define Si4455DummyChipPend1					Si4455ChipPend1
#define Si4455ChipReadyPend                     Si4455ChipPend2
#define Si4455CmdErrPend                        Si4455ChipPend3
#define Si4455StateChangePend                   Si4455ChipPend4
#define Si4455FifoUnderflowOverflowErrorPend    Si4455ChipPend5
#define Si4455CalPend                           Si4455ChipPend6
#define Si4455DummyChipPend7					Si4455ChipPend7

#define Si4455SyncDetectPend                    Si4455ModemPend0
#define Si4455PreambleDetectPend                Si4455ModemPend1
#define Si4455InvalidPreamblePend               Si4455ModemPend2
#define Si4455RssiPend                          Si4455ModemPend3
#define Si4455RssiJumpPend                      Si4455ModemPend4
#define Si4455InvalidSyncPend                   Si4455ModemPend5
#define Si4455PostambleDetectPend               Si4455ModemPend6
#define Si4455DummyModemPend7					Si4455ModemPend7

#define Si4455RxFifoAlmostFullPend              Si4455PhPend0
#define Si4455TxFifoAlmostEmptyPend             Si4455PhPend1
#define Si4455DummyPhPend2						Si4455PhPend2
#define Si4455Crc32ErrorPend                    Si4455PhPend3
#define Si4455PacketRxPend                      Si4455PhPend4
#define Si4455PacketSentPend                    Si4455PhPend5
#define Si4455DummyPhPend6						Si4455PhPend6
#define Si4455DummyPhPend7						Si4455PhPend7

/*!
 * Do NOT use SI_SEG_BDATA as that is not understood by SDCC!
 * Use BITS, WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY instead to allocate and
 * handle bit arrays in a convenient way.
 *
 * Allocate all 8bits if WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY macros
 * are to be used. Otherwise these macros would read/write bits that are
 * placed within that byte by the linker.
 */
BITS(Si4455PhPend, 0);
BITS(Si4455PhPend, 1);
BITS(Si4455PhPend, 2);
BITS(Si4455PhPend, 3);
BITS(Si4455PhPend, 4);
BITS(Si4455PhPend, 5);
BITS(Si4455PhPend, 6);
BITS(Si4455PhPend, 7);

BITS(Si4455ModemPend, 0);
BITS(Si4455ModemPend, 1);
BITS(Si4455ModemPend, 2);
BITS(Si4455ModemPend, 3);
BITS(Si4455ModemPend, 4);
BITS(Si4455ModemPend, 5);
BITS(Si4455ModemPend, 6);
BITS(Si4455ModemPend, 7);

BITS(Si4455ChipPend, 0);
BITS(Si4455ChipPend, 1);
BITS(Si4455ChipPend, 2);
BITS(Si4455ChipPend, 3);
BITS(Si4455ChipPend, 4);
BITS(Si4455ChipPend, 5);
BITS(Si4455ChipPend, 6);
BITS(Si4455ChipPend, 7);
/*!
 * This function is used to handle the assertion of nIRQ of the si4455 chip.
 *
 * @note This function can take up to 6 ms depending on the startup time of the
 * si4455 chip.
 *
 */
void si4455_nirq_process(void)
{
#ifdef SI4455_USER_CONFIG_USE_FRR_ABC_FOR_NIRQ
    SI_SEGMENT_VARIABLE(pendBits[3], uint8_t, SI_SEG_DATA);

    si4455_frr_read();
#else
    si4455_get_int_status(0, 0, 0);
    WRITE_TO_BIT_ARRAY(Si4455PhPend, Si4455Cmd.GET_INT_STATUS.PH_PEND);
    WRITE_TO_BIT_ARRAY(Si4455ModemPend, Si4455Cmd.GET_INT_STATUS.MODEM_PEND);
    WRITE_TO_BIT_ARRAY(Si4455ChipPend, Si4455Cmd.GET_INT_STATUS.CHIP_PEND);
#endif
}
