//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================


// USER INCLUDES
#include <SI_C8051F990_Register_Enums.h>
#include <stdio.h>

//-----------------------------------------------------------------------------
// Generic UART definitions to support both Keil and SDCC
//-----------------------------------------------------------------------------

#ifdef SDCC
#include <sdcc_stdio.h>
#endif

char *GETS (char *, uint16_t);

#ifdef __C51__
#define GETS gets
#endif

#ifdef SDCC
#include <sdcc_stdio.c>
#endif

//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN::ADINT (Conversion Complete Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(ADC0EOC_ISR, ADC0EOC_IRQn)
{
	static uint32_t accumulator = 0;    // accumulator for averaging
	static uint16_t measurements = 2048; // measurement counter
	uint32_t result=0;
	uint32_t mV;                        // measured voltage in mV

	ADC0CN_ADINT = 0;                              // clear ADC0 conv. complete flag

	accumulator += ADC0;
	measurements--;

	if(measurements == 0)
	{
	  measurements = 2048;
	  result = accumulator / 2048;
	  accumulator=0;

	  // The 10-bit ADC value is averaged across 2048 measurements.
	  // The measured voltage applied to P1.4 is then:
	  //
	  //                           Vref (mV)
	  //   measurement (mV) =   --------------- * result (bits)
	  //                       (2^10)-1 (bits)

	  mV =  result * 3300 / 1023;
	  printf("\f\nP0.6 voltage: %d mV", (uint16_t) mV);
	}
}

//-----------------------------------------------------------------------------
// VDDMON_ISR
//-----------------------------------------------------------------------------
//
// VDDMON ISR Content goes here. Remember to clear flag bits:
// VDM0CN::VDDOK (V<subscript>DD</subscript> Supply Status (Early Warning))
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(VDDMON_ISR, VDDMON_IRQn)
{

}


