//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB51_Register_Enums.h>
#include "InitDevice.h"

// USER PROTOTYPES
// USER FUNCTIONS

// $[Library Includes]
// [Library Includes]$

//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void enter_DefaultMode_from_RESET(void) {
    // $[Config Calls]
    // Save the SFRPAGE
    uint8_t SFRPAGE_save = SFRPAGE;
    WDT_0_enter_DefaultMode_from_RESET();
    PORTS_0_enter_DefaultMode_from_RESET();
    PORTS_1_enter_DefaultMode_from_RESET();
    PORTS_2_enter_DefaultMode_from_RESET();
    PBCFG_0_enter_DefaultMode_from_RESET();
    ADC_0_enter_DefaultMode_from_RESET();
    CLOCK_0_enter_DefaultMode_from_RESET();
    TIMER01_0_enter_DefaultMode_from_RESET();
    TIMER16_2_enter_DefaultMode_from_RESET();
    TIMER_SETUP_0_enter_DefaultMode_from_RESET();
    UART_0_enter_DefaultMode_from_RESET();
    INTERRUPT_0_enter_DefaultMode_from_RESET();
    // Restore the SFRPAGE
    SFRPAGE = SFRPAGE_save;
    // [Config Calls]$
}

//================================================================================
// WDT_0_enter_DefaultMode_from_RESET
//================================================================================
extern void WDT_0_enter_DefaultMode_from_RESET(void) {
    // $[Watchdog Timer Init Variable Declarations]
    // [Watchdog Timer Init Variable Declarations]$

    // $[WDTCN - Watchdog Timer Control]
    SFRPAGE = 0x00;
    //Disable Watchdog with key sequence
    WDTCN = 0xDE; //First key
    WDTCN = 0xAD; //Second key
    // [WDTCN - Watchdog Timer Control]$
}

//================================================================================
// PORTS_0_enter_DefaultMode_from_RESET
//================================================================================
extern void PORTS_0_enter_DefaultMode_from_RESET(void) {
    // $[P0 - Port 0 Pin Latch]
    // [P0 - Port 0 Pin Latch]$

    // $[P0MDOUT - Port 0 Output Mode]
    /***********************************************************************
     - P0.0 output is push-pull
     - P0.1 output is open-drain
     - P0.2 output is open-drain
     - P0.3 output is open-drain
     - P0.4 output is push-pull
     - P0.5 output is open-drain
     - P0.6 output is open-drain
     - P0.7 output is open-drain
     ***********************************************************************/
    SFRPAGE = 0x00;
    P0MDOUT = P0MDOUT_B0__PUSH_PULL | P0MDOUT_B1__OPEN_DRAIN
            | P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__OPEN_DRAIN
            | P0MDOUT_B4__PUSH_PULL | P0MDOUT_B5__OPEN_DRAIN
            | P0MDOUT_B6__OPEN_DRAIN | P0MDOUT_B7__OPEN_DRAIN;
    // [P0MDOUT - Port 0 Output Mode]$

    // $[P0MDIN - Port 0 Input Mode]
    /***********************************************************************
     - P0.0 pin is configured for digital mode
     - P0.1 pin is configured for analog mode
     - P0.2 pin is configured for analog mode
     - P0.3 pin is configured for analog mode
     - P0.4 pin is configured for digital mode
     - P0.5 pin is configured for digital mode
     - P0.6 pin is configured for analog mode
     - P0.7 pin is configured for analog mode
     ***********************************************************************/
    P0MDIN = P0MDIN_B0__DIGITAL | P0MDIN_B1__ANALOG | P0MDIN_B2__ANALOG
            | P0MDIN_B3__ANALOG | P0MDIN_B4__DIGITAL | P0MDIN_B5__DIGITAL
            | P0MDIN_B6__ANALOG | P0MDIN_B7__ANALOG;
    // [P0MDIN - Port 0 Input Mode]$

    // $[P0SKIP - Port 0 Skip]
    /***********************************************************************
     - P0.0 pin is skipped by the crossbar
     - P0.1 pin is not skipped by the crossbar
     - P0.2 pin is skipped by the crossbar
     - P0.3 pin is not skipped by the crossbar
     - P0.4 pin is not skipped by the crossbar
     - P0.5 pin is not skipped by the crossbar
     - P0.6 pin is not skipped by the crossbar
     - P0.7 pin is not skipped by the crossbar
     ***********************************************************************/
    P0SKIP = P0SKIP_B0__SKIPPED | P0SKIP_B1__NOT_SKIPPED
            | P0SKIP_B2__SKIPPED | P0SKIP_B3__NOT_SKIPPED
            | P0SKIP_B4__NOT_SKIPPED | P0SKIP_B5__NOT_SKIPPED
            | P0SKIP_B6__NOT_SKIPPED | P0SKIP_B7__NOT_SKIPPED;
    // [P0SKIP - Port 0 Skip]$

    // $[P0MASK - Port 0 Mask]
    // [P0MASK - Port 0 Mask]$

    // $[P0MAT - Port 0 Match]
    // [P0MAT - Port 0 Match]$

}

//================================================================================
// PORTS_1_enter_DefaultMode_from_RESET
//================================================================================
extern void PORTS_1_enter_DefaultMode_from_RESET(void) {
  // $[P1 - Port 1 Pin Latch]
  // [P1 - Port 1 Pin Latch]$

  // $[P1MDOUT - Port 1 Output Mode]
  /***********************************************************************
   - P1.0 output is open-drain
   - P1.1 output is open-drain
   - P1.2 output is open-drain
   - P1.3 output is open-drain
   - P1.4 output is open-drain
   - P1.5 output is open-drain
   - P1.6 output is open-drain
   ***********************************************************************/
  P1MDOUT = P1MDOUT_B0__OPEN_DRAIN | P1MDOUT_B1__OPEN_DRAIN
      | P1MDOUT_B2__OPEN_DRAIN | P1MDOUT_B3__OPEN_DRAIN | P1MDOUT_B4__OPEN_DRAIN
      | P1MDOUT_B5__OPEN_DRAIN | P1MDOUT_B6__OPEN_DRAIN;
  // [P1MDOUT - Port 1 Output Mode]$

  // $[P1MDIN - Port 1 Input Mode]
  /***********************************************************************
   - P1.0 pin is configured for digital mode
   - P1.1 pin is configured for digital mode
   - P1.2 pin is configured for digital mode
   - P1.3 pin is configured for analog mode
   - P1.4 pin is configured for analog mode
   - P1.5 pin is configured for digital mode
   - P1.6 pin is configured for digital mode
   ***********************************************************************/
  P1MDIN = P1MDIN_B0__DIGITAL | P1MDIN_B1__DIGITAL | P1MDIN_B2__DIGITAL
      | P1MDIN_B3__ANALOG | P1MDIN_B4__ANALOG | P1MDIN_B5__DIGITAL
      | P1MDIN_B6__DIGITAL;
  // [P1MDIN - Port 1 Input Mode]$

  // $[P1SKIP - Port 1 Skip]
  /***********************************************************************
   - P1.0 pin is not skipped by the crossbar
   - P1.1 pin is not skipped by the crossbar
   - P1.2 pin is not skipped by the crossbar
   - P1.3 pin is skipped by the crossbar
   - P1.4 pin is skipped by the crossbar
   - P1.5 pin is not skipped by the crossbar
   - P1.6 pin is not skipped by the crossbar
   - P1.7 pin is not skipped by the crossbar
   ***********************************************************************/
  P1SKIP = P1SKIP_B0__NOT_SKIPPED | P1SKIP_B1__NOT_SKIPPED
      | P1SKIP_B2__NOT_SKIPPED | P1SKIP_B3__SKIPPED | P1SKIP_B4__SKIPPED
      | P1SKIP_B5__NOT_SKIPPED | P1SKIP_B6__NOT_SKIPPED;
  // [P1SKIP - Port 1 Skip]$

  // $[P1MASK - Port 1 Mask]
  // [P1MASK - Port 1 Mask]$

  // $[P1MAT - Port 1 Match]
  // [P1MAT - Port 1 Match]$

}

//================================================================================
// PORTS_2_enter_DefaultMode_from_RESET
//================================================================================
extern void PORTS_2_enter_DefaultMode_from_RESET(void) {
    // $[P2 - Port 2 Pin Latch]
    // [P2 - Port 2 Pin Latch]$

    // $[P2MDOUT - Port 2 Output Mode]
    // [P2MDOUT - Port 2 Output Mode]$

    // $[P2MDIN - Port 2 Input Mode]
    /***********************************************************************
     - P2.0 pin is configured for digital mode
     ***********************************************************************/
    SFRPAGE = 0x20;
    P2MDIN = P2MDIN_B0__DIGITAL;
    // [P2MDIN - Port 2 Input Mode]$

}

//================================================================================
// PBCFG_0_enter_DefaultMode_from_RESET
//================================================================================
extern void PBCFG_0_enter_DefaultMode_from_RESET(void) {
    // $[XBR2 - Port I/O Crossbar 2]
    /***********************************************************************
     - Weak Pullups enabled
     - Crossbar enabled
     - UART1 I/O unavailable at Port pin
     - UART1 RTS1 unavailable at Port pin
     - UART1 CTS1 unavailable at Port pin
     ***********************************************************************/
    SFRPAGE = 0x00;
    XBR2 = XBR2_WEAKPUD__PULL_UPS_ENABLED | XBR2_XBARE__ENABLED
            | XBR2_URT1E__DISABLED | XBR2_URT1RTSE__DISABLED
            | XBR2_URT1CTSE__DISABLED;
    // [XBR2 - Port I/O Crossbar 2]$

    // $[PRTDRV - Port Drive Strength]
    // [PRTDRV - Port Drive Strength]$

    // $[XBR0 - Port I/O Crossbar 0]
    /***********************************************************************
     - UART0 TX0, RX0 routed to Port pins P0.4 and P0.5
     - SPI I/O unavailable at Port pins
     - SMBus 0 I/O unavailable at Port pins
     - CP0 unavailable at Port pin
     - Asynchronous CP0 unavailable at Port pin
     - CP1 unavailable at Port pin
     - Asynchronous CP1 unavailable at Port pin
     - SYSCLK unavailable at Port pin
     ***********************************************************************/
    XBR0 = XBR0_URT0E__ENABLED | XBR0_SPI0E__DISABLED | XBR0_SMB0E__DISABLED
            | XBR0_CP0E__DISABLED | XBR0_CP0AE__DISABLED | XBR0_CP1E__DISABLED
            | XBR0_CP1AE__DISABLED | XBR0_SYSCKE__DISABLED;
    // [XBR0 - Port I/O Crossbar 0]$

    // $[XBR1 - Port I/O Crossbar 1]
    // [XBR1 - Port I/O Crossbar 1]$

}

//================================================================================
// ADC_0_enter_DefaultMode_from_RESET
//================================================================================
extern void ADC_0_enter_DefaultMode_from_RESET(void) {
    // $[ADC0CN2 - ADC0 Control 2]
    /***********************************************************************
     - ADC0 conversion initiated on overflow of Timer 2
     - The ADC accumulator is over-written with the results of any conversion
     ***********************************************************************/
    SFRPAGE = 0x00;
    ADC0CN2 = ADC0CN2_ADCM__TIMER2 | ADC0CN2_PACEN__PAC_DISABLED;
    // [ADC0CN2 - ADC0 Control 2]$

    // $[ADC0CN1 - ADC0 Control 1]
    // [ADC0CN1 - ADC0 Control 1]$

    // $[ADC0MX - ADC0 Multiplexer Selection]
    /***********************************************************************
     - Select ADC0.9
     ***********************************************************************/
    ADC0MX = ADC0MX_ADC0MX__ADC0P9;
    // [ADC0MX - ADC0 Multiplexer Selection]$

    // $[ADC0CF2 - ADC0 Power Control]
    /***********************************************************************
     - The ADC0 ground reference is the internal GND pin
     - The ADC0 voltage reference is VDD * 34/64 (Range 2)
     - Power Up Delay Time = 0x08
     ***********************************************************************/
    ADC0CF2 = ADC0CF2_GNDSL__GND_PIN | ADC0CF2_REFSL__VDD_RANGE2
            | (0x08 << ADC0CF2_ADPWR__SHIFT);
    // [ADC0CF2 - ADC0 Power Control]$

    // $[ADC0CF1 - ADC0 Configuration]
    /***********************************************************************
     - Disable external voltage reference for ADC
     - Conversion Tracking Time = 0x0A
     ***********************************************************************/
    ADC0CF1 = ADC0CF1_RPCE__DISABLED | (0x0A << ADC0CF1_ADTK__SHIFT);
    // [ADC0CF1 - ADC0 Configuration]$

    // $[ADC0ASAL - ADC0 Autoscan Start Address Low Byte]
    // [ADC0ASAL - ADC0 Autoscan Start Address Low Byte]$

    // $[ADC0GTH - ADC0 Greater-Than High Byte]
    // [ADC0GTH - ADC0 Greater-Than High Byte]$

    // $[ADC0GTL - ADC0 Greater-Than Low Byte]
    // [ADC0GTL - ADC0 Greater-Than Low Byte]$

    // $[ADC0LTH - ADC0 Less-Than High Byte]
    // [ADC0LTH - ADC0 Less-Than High Byte]$

    // $[ADC0LTL - ADC0 Less-Than Low Byte]
    // [ADC0LTL - ADC0 Less-Than Low Byte]$

    // $[ADC0ASCF - ADC0 Autoscan Configuration]
    // [ADC0ASCF - ADC0 Autoscan Configuration]$

    // $[ADC0CN0 - ADC0 Control 0]
    /***********************************************************************
     - Enable ADC0
     - Power down when ADC is idle
     ***********************************************************************/
    ADC0CN0 |= ADC0CN0_ADEN__ENABLED | ADC0CN0_IPOEN__POWER_DOWN;
    // [ADC0CN0 - ADC0 Control 0]$

}

//================================================================================
// CLOCK_0_enter_DefaultMode_from_RESET
//================================================================================
extern void CLOCK_0_enter_DefaultMode_from_RESET(void) {
    // $[HFOSC1 Setup]
    // [HFOSC1 Setup]$

    // $[CLKSEL - Clock Select]
    /***********************************************************************
     - Clock derived from the Internal High Frequency Oscillator 0
     - SYSCLK is equal to selected clock source divided by 1
     ***********************************************************************/
    SFRPAGE = 0x0;
    CLKSEL = CLKSEL_CLKSL__HFOSC0_clk24p5 | CLKSEL_CLKDIV__SYSCLK_DIV_1;
    while ((CLKSEL & CLKSEL_DIVRDY__BMASK) == CLKSEL_DIVRDY__NOT_READY);
    // [CLKSEL - Clock Select]$

    // $[CLKGRP0 - Clock Group 0]
    /***********************************************************************
     - Enable SAR clock derived from the Internal High Frequency Oscillator 0
     - SYSCLK is equal to selected clock source divided by 1
     ***********************************************************************/
    CLKGRP0 |= CLKGRP0_EN_SARCLK__ENABLE;
    // [CLKGRP0 - Clock Group 0]$
}

//================================================================================
// TIMER01_0_enter_DefaultMode_from_RESET
//================================================================================
extern void TIMER01_0_enter_DefaultMode_from_RESET(void) {
    // $[Timer Initialization]
    //Save Timer Configuration
    uint8_t TCON_save;

    SFRPAGE = 0x00;
    TCON_save = TCON;
    //Stop Timers
    TCON &= ~TCON_TR0__BMASK & ~TCON_TR1__BMASK;

    // [Timer Initialization]$

    // $[TH0 - Timer 0 High Byte]
    // [TH0 - Timer 0 High Byte]$

    // $[TL0 - Timer 0 Low Byte]
    // [TL0 - Timer 0 Low Byte]$

    // $[TH1 - Timer 1 High Byte]
    /***********************************************************************
     - Timer 1 High Byte = 0xF7
     ***********************************************************************/
    TH1 = (0xF7 << TH1_TH1__SHIFT);
    // [TH1 - Timer 1 High Byte]$

    // $[TL1 - Timer 1 Low Byte]
    // [TL1 - Timer 1 Low Byte]$

    // $[Timer Restoration]
    //Restore Timer Configuration
    TCON |= (TCON_save & TCON_TR0__BMASK) | (TCON_save & TCON_TR1__BMASK);

    // [Timer Restoration]$

}

//================================================================================
// TIMER16_2_enter_DefaultMode_from_RESET
//================================================================================
extern void TIMER16_2_enter_DefaultMode_from_RESET(void) {
    // $[Timer Initialization]
    // Save Timer Configuration
    uint8_t TMR2CN0_TR2_save;

    SFRPAGE = 0x00;
    TMR2CN0_TR2_save = TMR2CN0 & TMR2CN0_TR2__BMASK;
    // Stop Timer
    TMR2CN0 &= ~(TMR2CN0_TR2__BMASK);
    // [Timer Initialization]$

    // $[TMR2CN1 - Timer 2 Control 1]
    // [TMR2CN1 - Timer 2 Control 1]$

    // $[TMR2CN0 - Timer 2 Control]
    // [TMR2CN0 - Timer 2 Control]$

    // $[TMR2H - Timer 2 High Byte]
    /***********************************************************************
     - Timer 2 High Byte = 0xFF
     ***********************************************************************/
    TMR2H = (0x83 << TMR2H_TMR2H__SHIFT);
    // [TMR2H - Timer 2 High Byte]$

    // $[TMR2L - Timer 2 Low Byte]
    /***********************************************************************
     - Timer 2 Low Byte = 0x34
     ***********************************************************************/
    TMR2L = (0x62 << TMR2L_TMR2L__SHIFT);
    // [TMR2L - Timer 2 Low Byte]$

    // $[TMR2RLH - Timer 2 Reload High Byte]
    /***********************************************************************
     - Timer 2 Reload High Byte = 0xFF
     ***********************************************************************/
    TMR2RLH = (0x83 << TMR2RLH_TMR2RLH__SHIFT);
    // [TMR2RLH - Timer 2 Reload High Byte]$

    // $[TMR2RLL - Timer 2 Reload Low Byte]
    /***********************************************************************
     - Timer 2 Reload Low Byte = 0x34
     ***********************************************************************/
    TMR2RLL = (0x62 << TMR2RLL_TMR2RLL__SHIFT);
    // [TMR2RLL - Timer 2 Reload Low Byte]$

    // $[TMR2CN0]
    /***********************************************************************
     - Start Timer 2 running
     ***********************************************************************/
    TMR2CN0 |= TMR2CN0_TR2__RUN;
    // [TMR2CN0]$

}

//================================================================================
// TIMER_SETUP_0_enter_DefaultMode_from_RESET
//================================================================================
extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void) {
    // $[CKCON0 - Clock Control 0]
    // [CKCON0 - Clock Control 0]$

    // $[CKCON1 - Clock Control 1]
    // [CKCON1 - Clock Control 1]$

    // $[TMOD - Timer 0/1 Mode]
    /***********************************************************************
     - Mode 0, 13-bit Counter/Timer
     - Mode 2, 8-bit Counter/Timer with Auto-Reload
     - Timer Mode
     - Timer 0 enabled when TR0 = 1 irrespective of INT0 logic level
     - Timer Mode
     - Timer 1 enabled when TR1 = 1 irrespective of INT1 logic level
     ***********************************************************************/
    SFRPAGE = 0x00;
    TMOD = TMOD_T0M__MODE0 | TMOD_T1M__MODE2 | TMOD_CT0__TIMER
            | TMOD_GATE0__DISABLED | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;
    // [TMOD - Timer 0/1 Mode]$

    // $[TCON - Timer 0/1 Control]
    /***********************************************************************
     - Start Timer 1 running
     ***********************************************************************/
    TCON |= TCON_TR1__RUN;
    // [TCON - Timer 0/1 Control]$

}

//================================================================================
// UART_0_enter_DefaultMode_from_RESET
//================================================================================
extern void UART_0_enter_DefaultMode_from_RESET(void) {
    // $[SCON0 - UART0 Serial Port Control]
    // [SCON0 - UART0 Serial Port Control]$

}

//================================================================================
// INTERRUPT_0_enter_DefaultMode_from_RESET
//================================================================================
extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void) {
    // $[EIE1 - Extended Interrupt Enable 1]
    /***********************************************************************
     - Enable interrupt requests generated by the ADINT flag
     - Disable ADC0 Window Comparison interrupt
     - Disable CP0 interrupts
     - Disable CP1 interrupts
     - Disable all Port Match interrupts
     - Disable all PCA0 interrupts
     - Disable all SMB0 interrupts
     - Disable Timer 3 interrupts
     ***********************************************************************/
    SFRPAGE = 0x00;
    EIE1 = EIE1_EADC0__ENABLED | EIE1_EWADC0__DISABLED | EIE1_ECP0__DISABLED
            | EIE1_ECP1__DISABLED | EIE1_EMAT__DISABLED | EIE1_EPCA0__DISABLED
            | EIE1_ESMB0__DISABLED | EIE1_ET3__DISABLED;
    // [EIE1 - Extended Interrupt Enable 1]$

    // $[EIE2 - Extended Interrupt Enable 2]
    // [EIE2 - Extended Interrupt Enable 2]$

    // $[EIP1H - Extended Interrupt Priority 1 High]
    // [EIP1H - Extended Interrupt Priority 1 High]$

    // $[EIP1 - Extended Interrupt Priority 1 Low]
    // [EIP1 - Extended Interrupt Priority 1 Low]$

    // $[EIP2 - Extended Interrupt Priority 2]
    // [EIP2 - Extended Interrupt Priority 2]$

    // $[EIP2H - Extended Interrupt Priority 2 High]
    // [EIP2H - Extended Interrupt Priority 2 High]$

    // $[IE - Interrupt Enable]
    /***********************************************************************
     - Enable each interrupt according to its individual mask setting
     - Disable external interrupt 0
     - Disable external interrupt 1
     - Disable all SPI0 interrupts
     - Disable all Timer 0 interrupt
     - Disable all Timer 1 interrupt
     - Disable Timer 2 interrupt
     - Disable UART0 interrupt
     ***********************************************************************/
    IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED
            | IE_ESPI0__DISABLED | IE_ET0__DISABLED | IE_ET1__DISABLED
            | IE_ET2__DISABLED | IE_ES0__DISABLED;
    // [IE - Interrupt Enable]$

    // $[IP - Interrupt Priority]
    // [IP - Interrupt Priority]$

    // $[IPH - Interrupt Priority High]
    // [IPH - Interrupt Priority High]$

}
