//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include <SI_C8051F970_Register_Enums.h>
#include "InitDevice.h"

// USER PROTOTYPES
// USER FUNCTIONS

// $[Library Includes]
// [Library Includes]$

//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void enter_DefaultMode_from_RESET(void)
{
  // $[Config Calls]
  // Save the SFRPAGE
  uint8_t SFRPAGE_save = SFRPAGE;
  PCA_0_enter_DefaultMode_from_RESET();
  VREG_0_enter_DefaultMode_from_RESET();
  PORTS_0_enter_DefaultMode_from_RESET();
  PBCFG_0_enter_DefaultMode_from_RESET();
  VREF_0_enter_DefaultMode_from_RESET();
  HFOSC_0_enter_DefaultMode_from_RESET();
  RSTSRC_0_enter_DefaultMode_from_RESET();
  CLOCK_0_enter_DefaultMode_from_RESET();
  TIMER01_0_enter_DefaultMode_from_RESET();
  TIMER16_2_enter_DefaultMode_from_RESET();
  TIMER_SETUP_0_enter_DefaultMode_from_RESET();
  INTERRUPT_0_enter_DefaultMode_from_RESET();
  // Restore the SFRPAGE
  SFRPAGE = SFRPAGE_save;
  // [Config Calls]$

}

extern void PCA_0_enter_DefaultMode_from_RESET(void)
{
  // $[Watchdog Disable]
  // Stop Watchdog
  // If MCU is reset by WDT before it runs to main(), please disable it in SILABS_STARTUP.A51
  SFRPAGE = 0x00;
  PCA0MD &= ~PCA0MD_WDTE__BMASK;

  // [Watchdog Disable]$

  // $[PCA0CPM0 - PCA Channel 0 Capture/Compare Mode 0]
  /***********************************************************************
   - Enable a Capture/Compare Flag interrupt request when CCF0 is set
   - Disable match function
   - Disable negative edge capture
   - 8 to 11-bit PWM selected
   - Enable positive edge capture
   - Disable comparator function
   - Disable PWM function
   - Disable toggle function
   ***********************************************************************/
  PCA0CPM0 = PCA0CPM0_ECCF__ENABLED | PCA0CPM0_MAT__DISABLED
      | PCA0CPM0_CAPN__DISABLED | PCA0CPM0_PWM16__8_BIT | PCA0CPM0_CAPP__ENABLED
      | PCA0CPM0_ECOM__DISABLED | PCA0CPM0_PWM__DISABLED
      | PCA0CPM0_TOG__DISABLED;
  // [PCA0CPM0 - PCA Channel 0 Capture/Compare Mode 0]$

  // $[PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]
  // [PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]$

  // $[PCA0CPH0 - PCA Channel 0 Capture Module High Byte]
  // [PCA0CPH0 - PCA Channel 0 Capture Module High Byte]$

  // $[PCA0CPM1 - PCA Channel 1 Capture/Compare Mode]
  // [PCA0CPM1 - PCA Channel 1 Capture/Compare Mode]$

  // $[PCA0CPL1 - PCA Channel 1 Capture Module Low Byte]
  // [PCA0CPL1 - PCA Channel 1 Capture Module Low Byte]$

  // $[PCA0CPH1 - PCA Channel 1 Capture Module High Byte]
  // [PCA0CPH1 - PCA Channel 1 Capture Module High Byte]$

  // $[PCA0CPM2 - PCA Channel 2 Capture/Compare Mode]
  // [PCA0CPM2 - PCA Channel 2 Capture/Compare Mode]$

  // $[PCA0CPL2 - PCA Channel 2 Capture Module Low Byte]
  // [PCA0CPL2 - PCA Channel 2 Capture Module Low Byte]$

  // $[PCA0CPH2 - PCA Channel 2 Capture Module High Byte]
  // [PCA0CPH2 - PCA Channel 2 Capture Module High Byte]$

  // $[PCA0CN - PCA Control]
  /***********************************************************************
   - Start the PCA Counter/Timer running
   ***********************************************************************/
  PCA0CN = PCA0CN_CR__RUN;
  // [PCA0CN - PCA Control]$

  // $[PCA0L - PCA Counter/Timer Low Byte]
  // [PCA0L - PCA Counter/Timer Low Byte]$

  // $[PCA0H - PCA Counter/Timer High Byte]
  // [PCA0H - PCA Counter/Timer High Byte]$

  // $[PCA0PWM - PCA PWM Configuration]
  // [PCA0PWM - PCA PWM Configuration]$

  // $[PCA0MD - PCA Mode]
  /***********************************************************************
   - Timer 0 overflow
   ***********************************************************************/
  PCA0MD &= ~PCA0MD_CPS__FMASK;
  PCA0MD |= PCA0MD_CPS__T0_OVERFLOW;
  // [PCA0MD - PCA Mode]$

  // $[WDT - Watchdog run Control]
  // [WDT - Watchdog run Control]$

}

extern void VREG_0_enter_DefaultMode_from_RESET(void)
{
  // $[REG0CN - Voltage Regulator Control]
  /***********************************************************************
   - Enable the precision High Frequency Oscillator bias
   ***********************************************************************/
  REG0CN = REG0CN_OSCBIAS__ENABLED;
  // [REG0CN - Voltage Regulator Control]$

}

extern void PBCFG_0_enter_DefaultMode_from_RESET(void)
{
  // $[XBR1 - Port I/O Crossbar 1]
  /***********************************************************************
   - Weak Pullups enabled 
   - Crossbar enabled
   - T0 unavailable at Port pin
   - T1 unavailable at Port pin
   ***********************************************************************/
  XBR1 = XBR1_WEAKPUD__PULL_UPS_ENABLED | XBR1_XBARE__ENABLED
      | XBR1_T0E__DISABLED | XBR1_T1E__DISABLED;
  // [XBR1 - Port I/O Crossbar 1]$

  // $[XBR0 - Port I/O Crossbar 0]
  /***********************************************************************
   - SMBus0 I/O unavailable at Port pins
   - UART I/O unavailable at Port pin
   - SPI I/O unavailable at Port pins
   - SYSCLK unavailable at Port pin
   - CEX0 routed to Port pin
   - ECI unavailable at Port pin
   ***********************************************************************/
  XBR0 = XBR0_SMB0E__DISABLED | XBR0_URT0E__DISABLED | XBR0_SPI0E__DISABLED
      | XBR0_SYSCKE__DISABLED | XBR0_PCA0ME__CEX0 | XBR0_ECIE__DISABLED;
  // [XBR0 - Port I/O Crossbar 0]$

}

extern void VREF_0_enter_DefaultMode_from_RESET(void)
{
  // $[REF0CN - Voltage Reference Control]
  /***********************************************************************
   - Disable the Temperature Sensor
   - The ADC0 voltage reference is the internal 1.65 V high speed voltage
   reference
   ***********************************************************************/
  SFRPAGE = 0x00;
  REF0CN = REF0CN_TEMPE__TEMP_DISABLED | REF0CN_REFSL__HIGH_SPEED_VREF;
  // [REF0CN - Voltage Reference Control]$

}

extern void HFOSC_0_enter_DefaultMode_from_RESET(void)
{
  // $[OSCICL - High Frequency Oscillator Calibration]
  // [OSCICL - High Frequency Oscillator Calibration]$

  // $[OSCICN - High Frequency Oscillator Control]
  /***********************************************************************
   - High Frequency Oscillator enabled
   ***********************************************************************/
  OSCICN |= OSCICN_IOSCEN__ENABLED;
  // [OSCICN - High Frequency Oscillator Control]$

}

extern void CLOCK_0_enter_DefaultMode_from_RESET(void)
{
  // $[CLKSEL - Clock Select]
  /***********************************************************************
   - SYSCLK is equal to selected clock source divided by 8
   - Clock derived from the internal precision High-Frequency Oscillator
   ***********************************************************************/
  CLKSEL = CLKSEL_CLKDIV__SYSCLK_DIV_8 | CLKSEL_CLKSL__HFOSC;
  // Wait for the clock to be ready
  while ((CLKSEL & CLKSEL_CLKRDY__BMASK) != CLKSEL_CLKRDY__SET)
    ;
  // [CLKSEL - Clock Select]$

  // $[PCLKEN - Low Power Peripheral Clock Enable]
  // [PCLKEN - Low Power Peripheral Clock Enable]$

  // $[CLKMODE -  Clock Mode]
  // [CLKMODE -  Clock Mode]$

}

extern void PORTS_0_enter_DefaultMode_from_RESET(void)
{
  // $[P0 - Port 0 Pin Latch]
  // [P0 - Port 0 Pin Latch]$

  // $[P0MDOUT - Port 0 Output Mode]
  /***********************************************************************
   - P0.0 output is open-drain
   - P0.1 output is push-pull
   - P0.2 output is open-drain
   - P0.3 output is open-drain
   - P0.4 output is open-drain
   - P0.5 output is open-drain
   - P0.6 output is open-drain
   - P0.7 output is open-drain
   ***********************************************************************/
  SFRPAGE = 0x0F;
  P0MDOUT = P0MDOUT_B0__OPEN_DRAIN | P0MDOUT_B1__PUSH_PULL
      | P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__OPEN_DRAIN | P0MDOUT_B4__OPEN_DRAIN
      | P0MDOUT_B5__OPEN_DRAIN | P0MDOUT_B6__OPEN_DRAIN
      | P0MDOUT_B7__OPEN_DRAIN;
  // [P0MDOUT - Port 0 Output Mode]$

  // $[P0MDIN - Port 0 Input Mode]
  // [P0MDIN - Port 0 Input Mode]$

  // $[P0SKIP - Port 0 Skip]
  /***********************************************************************
   - P0.0 pin is skipped by the crossbar
   - P0.1 pin is skipped by the crossbar
   - P0.2 pin is skipped by the crossbar
   - P0.3 pin is not skipped by the crossbar
   - P0.4 pin is not skipped by the crossbar
   - P0.5 pin is not skipped by the crossbar
   - P0.6 pin is not skipped by the crossbar
   - P0.7 pin is not skipped by the crossbar
   ***********************************************************************/
  P0SKIP = P0SKIP_B0__SKIPPED | P0SKIP_B1__SKIPPED | P0SKIP_B2__SKIPPED
      | P0SKIP_B3__NOT_SKIPPED | P0SKIP_B4__NOT_SKIPPED | P0SKIP_B5__NOT_SKIPPED
      | P0SKIP_B6__NOT_SKIPPED | P0SKIP_B7__NOT_SKIPPED;
  // [P0SKIP - Port 0 Skip]$

  // $[P0MASK - Port 0 Mask]
  // [P0MASK - Port 0 Mask]$

  // $[P0MAT - Port 0 Match]
  // [P0MAT - Port 0 Match]$

  // $[P0DRV - Port 0 Drive Strength]
  // [P0DRV - Port 0 Drive Strength]$

}

extern void RSTSRC_0_enter_DefaultMode_from_RESET(void)
{
  // $[RSTSRC - Reset Source]
  /***********************************************************************
   - A missing clock detector reset occurred
   - A power-on or supply monitor reset occurred
   - A RTC alarm or oscillator fail reset did not occur
   - A flash error reset did not occur
   - The /RST pin did not cause the last reset
   - A watchdog timer overflow reset did not occur
   ***********************************************************************/
  RSTSRC = RSTSRC_MCDRSF__SET | RSTSRC_PORSF__SET | RSTSRC_RTC0RE__NOT_SET
      | RSTSRC_FERROR__NOT_SET | RSTSRC_PINRSF__NOT_SET
      | RSTSRC_WDTRSF__NOT_SET;
  // [RSTSRC - Reset Source]$

}

extern void TIMER01_0_enter_DefaultMode_from_RESET(void)
{
  // $[Timer Initialization]
  //Save Timer Configuration
  uint8_t TCON_save;
  TCON_save = TCON;
  //Stop Timers
  TCON &= ~TCON_TR0__BMASK & ~TCON_TR1__BMASK;

  // [Timer Initialization]$

  // $[TH0 - Timer 0 High Byte]
  /***********************************************************************
   - Timer 0 High Byte = 0xE1
   ***********************************************************************/
  TH0 = (0xE1 << TH0_TH0__SHIFT);
  // [TH0 - Timer 0 High Byte]$

  // $[TL0 - Timer 0 Low Byte]
  /***********************************************************************
   - Timer 0 Low Byte = 0x0B
   ***********************************************************************/
  TL0 = (0x0B << TL0_TL0__SHIFT);
  // [TL0 - Timer 0 Low Byte]$

  // $[TH1 - Timer 1 High Byte]
  // [TH1 - Timer 1 High Byte]$

  // $[TL1 - Timer 1 Low Byte]
  // [TL1 - Timer 1 Low Byte]$

  // $[Timer Restoration]
  //Restore Timer Configuration
  TCON |= (TCON_save & TCON_TR0__BMASK) | (TCON_save & TCON_TR1__BMASK);

  // [Timer Restoration]$

}

extern void TIMER16_2_enter_DefaultMode_from_RESET(void)
{
  // $[Timer Initialization]
  // Save Timer Configuration
  uint8_t TMR2CN_TR2_save;
  TMR2CN_TR2_save = TMR2CN & TMR2CN_TR2__BMASK;
  // Stop Timer
  TMR2CN &= ~(TMR2CN_TR2__BMASK);
  // [Timer Initialization]$

  // $[TMR2CN - Timer 2 Control]
  // [TMR2CN - Timer 2 Control]$

  // $[TMR2H - Timer 2 High Byte]
  /***********************************************************************
   - Timer 2 High Byte = 0xE8
   ***********************************************************************/
  TMR2H = (0xE8 << TMR2H_TMR2H__SHIFT);
  // [TMR2H - Timer 2 High Byte]$

  // $[TMR2L - Timer 2 Low Byte]
  /***********************************************************************
   - Timer 2 Low Byte = 0x13
   ***********************************************************************/
  TMR2L = (0x13 << TMR2L_TMR2L__SHIFT);
  // [TMR2L - Timer 2 Low Byte]$

  // $[TMR2RLH - Timer 2 Reload High Byte]
  /***********************************************************************
   - Timer 2 Reload High Byte = 0xFD
   ***********************************************************************/
  TMR2RLH = (0xFD << TMR2RLH_TMR2RLH__SHIFT);
  // [TMR2RLH - Timer 2 Reload High Byte]$

  // $[TMR2RLL - Timer 2 Reload Low Byte]
  /***********************************************************************
   - Timer 2 Reload Low Byte = 0x02
   ***********************************************************************/
  TMR2RLL = (0x02 << TMR2RLL_TMR2RLL__SHIFT);
  // [TMR2RLL - Timer 2 Reload Low Byte]$

  // $[TMR2CN]
  /***********************************************************************
   - Start Timer 2 running
   ***********************************************************************/
  TMR2CN |= TMR2CN_TR2__RUN;
  // [TMR2CN]$

  // $[Timer Restoration]
  // Restore Timer Configuration
  TMR2CN |= TMR2CN_TR2_save;
  // [Timer Restoration]$

}

extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void)
{
  // $[CKCON - Clock Control]
  /***********************************************************************
   - System clock divided by 12
   - Counter/Timer 0 uses the system clock
   - Timer 2 high byte uses the clock defined by the T2XCLK bit in TMR2CN
   - Timer 2 low byte uses the system clock
   - Timer 3 high byte uses the clock defined by the T3XCLK bit in TMR3CN
   - Timer 3 low byte uses the clock defined by the T3XCLK bit in TMR3CN
   - Timer 1 uses the clock defined by the prescale field, SCA
   ***********************************************************************/
  CKCON = CKCON_SCA__SYSCLK_DIV_12 | CKCON_T0M__SYSCLK
      | CKCON_T2MH__EXTERNAL_CLOCK | CKCON_T2ML__SYSCLK
      | CKCON_T3MH__EXTERNAL_CLOCK | CKCON_T3ML__EXTERNAL_CLOCK
      | CKCON_T1M__PRESCALE;
  // [CKCON - Clock Control]$

  // $[TMOD - Timer 0/1 Mode]
  /***********************************************************************
   - Mode 2, 8-bit Counter/Timer with Auto-Reload
   - Timer Mode
   - Timer 0 enabled when TR0 = 1 irrespective of /INT0 logic level
   - Mode 0, 13-bit Counter/Timer
   - Timer Mode
   - Timer 1 enabled when TR1 = 1 irrespective of /INT1 logic level
   ***********************************************************************/
  TMOD = TMOD_T0M__MODE2 | TMOD_CT0__TIMER | TMOD_GATE0__DISABLED
      | TMOD_T1M__MODE0 | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;
  // [TMOD - Timer 0/1 Mode]$

  // $[TCON - Timer 0/1 Control]
  /***********************************************************************
   - Start Timer 0 running
   ***********************************************************************/
  TCON |= TCON_TR0__RUN;
  // [TCON - Timer 0/1 Control]$

}

extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void)
{
  // $[EIE1 - Extended Interrupt Enable 1]
  /***********************************************************************
   - Disable ADC0 Conversion Complete interrupt
   - Disable DMA0 interrupts
   - Disable DMA0M interrupts
   - Enable interrupt requests generated by PCA0
   - Disable RTC Alarm interrupts
   - Disable all SMB0 interrupts
   - Disable Timer 3 interrupts
   - Disable ADC0 Window Comparison interrupt
   ***********************************************************************/
  EIE1 = EIE1_EADC0__DISABLED | EIE1_EDMA0__DISABLED | EIE1_EDMA0M__DISABLED
      | EIE1_EPCA0__ENABLED | EIE1_ERTC0A__DISABLED | EIE1_ESMB0__DISABLED
      | EIE1_ET3__DISABLED | EIE1_EWADC0__DISABLED;
  // [EIE1 - Extended Interrupt Enable 1]$

  // $[EIP1 - Extended Interrupt Priority 1]
  // [EIP1 - Extended Interrupt Priority 1]$

  // $[IE - Interrupt Enable]
  /***********************************************************************
   - Enable each interrupt according to its individual mask setting
   - Disable external interrupt 0
   - Disable external interrupt 1
   - Disable all SPI0 interrupts
   - Disable all Timer 0 interrupt
   - Disable all Timer 1 interrupt
   - Disable Timer 2 interrupt
   - Disable UART0 interrupt
   ***********************************************************************/
  IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED | IE_ESPI0__DISABLED
      | IE_ET0__DISABLED | IE_ET1__DISABLED | IE_ET2__DISABLED
      | IE_ES0__DISABLED;
  // [IE - Interrupt Enable]$

  // $[IP - Interrupt Priority]
  // [IP - Interrupt Priority]$

  // $[EIE2 - Extended Interrupt Enable 2]
  // [EIE2 - Extended Interrupt Enable 2]$

  // $[EIP2 - Extended Interrupt Priority 2]
  // [EIP2 - Extended Interrupt Priority 2]$

}

