//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

         
// USER INCLUDES            
#include <SI_EFM8BB52_Register_Enums.h>


//-----------------------------------------------------------------------------
// Global VARIABLES
//-----------------------------------------------------------------------------
static uint8_t vrefGainIndex = 0; // Index to track current VREF setting
uint8_t vrefUpdate = 0;           // Flag to send updated VREF info via UART
uint16_t vref = 1200;             // Initial value set in InitDevice.c

//-----------------------------------------------------------------------------
// INT0_ISR
//-----------------------------------------------------------------------------
//
// INT0 ISR Content goes here. Remember to clear flag bits:
// TCON::IE0 (External Interrupt 0)
//
// Whenever a negative edge appears on P0.2, increment VREF gain index.
// The interrupt pending flag is automatically cleared by vectoring to the ISR
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(INT0_ISR, INT0_IRQn)
{
    uint8_t SFRPAGE_save = SFRPAGE;

    switch (vrefGainIndex)
    {
        case 0:
            vref = 1650;
            vrefGainIndex = 1;
            break;
        case 1:
            vref = 1800;
            vrefGainIndex = 2;
            break;
        case 2:
            vref = 2400;
            vrefGainIndex = 3;
            break;
        case 3:
            vref = 1200;
            vrefGainIndex = 0;
            break;
    }

    SFRPAGE = 0x00;
    REF0CN = (REF0CN & ~REF0CN_GAIN__FMASK) | (vrefGainIndex << REF0CN_GAIN__SHIFT);
    SFRPAGE = SFRPAGE_save;

    vrefUpdate = 0x1;
}

//-----------------------------------------------------------------------------
// INT1_ISR
//-----------------------------------------------------------------------------
//
// INT1 ISR Content goes here. Remember to clear flag bits:
// TCON::IE1 (External Interrupt 1)
//
// Whenever a negative edge appears on P0.3, decrement VREF gain index.
// The interrupt pending flag is automatically cleared by vectoring to the ISR
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(INT1_ISR, INT1_IRQn)
{
    uint8_t SFRPAGE_save = SFRPAGE;

    switch (vrefGainIndex)
    {
        case 0:
            vref = 2400;
            vrefGainIndex = 3;
            break;
        case 1:
            vref = 1200;
            vrefGainIndex = 0;
            break;
        case 2:
            vref = 1650;
            vrefGainIndex = 1;
            break;
        case 3:
            vref = 1800;
            vrefGainIndex = 2;
            break;
    }

    SFRPAGE = 0x00;
    REF0CN = (REF0CN & ~REF0CN_GAIN__FMASK) | (vrefGainIndex << REF0CN_GAIN__SHIFT);
    SFRPAGE = SFRPAGE_save;

    vrefUpdate = 0x1;
}
