//=========================================================
// src/Interupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_C8051F850_Register_Enums.h>

//-----------------------------------------------------------------------------
// Global Constants
//-----------------------------------------------------------------------------
// Configurator set for HFOSC/8 =
#define SYSCLK     3062000
#define PULSES_PER_TOGGLE          100 // Arbitrary number of pulses in the
                                       // input pin necessary to create an
                                       // interrupt.
                                       // Limited to 0x1FFF or 8191d for a
                                       // 13-bit timer
// reload value is determined by pulses per toggle;
#define RELOAD  (0x2000 - PULSES_PER_TOGGLE)
#define TIMER0_RELOAD_HIGH    RELOAD >>5
#define TIMER0_RELOAD_LOW     RELOAD & 0x1F

//-----------------------------------------------------------------------------
// Pin Definitions
//-----------------------------------------------------------------------------
SI_SBIT(LED1, SFR_P1, 0);                 // DS5 P1.0 LED

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
// Here we process the Timer0 interrupt and toggle the LED
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(TIMER0_ISR, TIMER0_IRQn)
{
	   LED1 = !LED1;                       // Toggle the LED

	   TH0 = TIMER0_RELOAD_HIGH;           // Reinit Timer0 High register
	   TL0 = TIMER0_RELOAD_LOW;            // Reinit Timer0 Low register
}


